/**
 * dacs-sdk — reusable runtime for building DACS (Demos Agent Commerce
 * Standards) agents across the Identify → Vet → Negotiate → Settle → Verify
 * lifecycle.
 *
 * T1 scaffold: this exports the substrate seam (SubstrateAdapter + DemosAdapter)
 * and package metadata. The agent-facing public API (`createAgent`,
 * `publishListing`, `discover`, `runSession`, `verifyBundle`, `getReputation`)
 * is designed in T4 — see IMPLEMENTATION.md.
 */

export { VERSION, DACS_SPEC_VERSION } from "./version.js";
export {
  FINALITY_COMMITMENT_SEPARATOR,
  finalityCommitmentAddress,
  commitFixedPriceAgreement,
  type CommitmentVerificationDisposition,
  type CommitmentSignatureVerificationInput,
  type CommitmentSignatureVerifier,
  type AnchoredFinalityCommitment,
  type FinalityCommitmentLookup,
  type FinalityCommitmentProvider,
  type CommitFixedPriceAgreementInput,
  type FinalizedAgreementCommitment,
} from "./negotiate/commitment.js";
export {
  deriveFixedPriceAgreement,
  signFixedPriceAgreement,
  type VerifiedListingInput,
  type FixedPricePartyInput,
  type FixedPriceAgreementInput,
  type UnsignedAgreementArtifact,
  type AgreementSigner,
} from "./negotiate/fixedPrice.js";

export {
  DacsError,
  NotImplementedError,
  TransientError,
  CounterpartyError,
  SubstrateError,
  faultCategory,
  type FaultCategory,
} from "./errors.js";

// Foundation (T2): canonical form, decimals, content hashing, domain-separated signing.
export {
  canonicalize,
  canonicalizeDecimal,
  assertPositiveAmount,
  baseUnits,
  encodeAddressSegment,
  decodeAddressSegment,
  listingAddress,
  logicalToStorageProgramName,
  storAddress,
  bundleAddress,
  sha256Hex,
  stripSignature,
  canonicalSignedScope,
  contentHash,
} from "./canonical/index.js";
export {
  privateKeyFromSeed,
  publicKeyFromSeed,
  publicKeyFromRaw,
  rawPublicKey,
  ed25519Sign,
  ed25519Verify,
  SIGNATURE_DOMAIN_SEPARATORS,
  type DomainSeparator,
  COMPOSITE_DOMAIN_SEPARATORS,
  type CompositeDomainSeparator,
  isRegisteredSeparator,
  isCompositeSeparator,
  dacsXSeparator,
  signedBytes,
  signArtifact,
  verifyArtifact,
  sessionBindingBytes,
  signSessionBinding,
  verifySessionBinding,
  autoAcceptInstanceBytes,
  signAutoAcceptInstance,
  verifyAutoAcceptInstance,
} from "./crypto/index.js";

// Types only — the `DemosAdapter` *value* lives on the
// "@kynesyslabs/dacs/substrate" subpath so this top-level barrel stays free of
// an eager @kynesyslabs/demosdk load (its ESM packaging breaks plain-Node-ESM
// consumers of the pure/verify surface). createAgent lazy-loads it when needed.
export type {
  DemosAdapterConfig,
  SubstrateAdapter,
  AnchorRef,
  ProxyFetchRequest,
  ProxyFetchResult,
  ResolvedIdentity,
} from "./substrate/index.js";

// CLI helpers (pure/read-only by default). The executable entry is `dacs`.
export {
  formatDoctorText,
  redactRpcUrl,
  redactSecret,
  runDoctor,
  sanitizeText,
  type DoctorAdapter,
  type DoctorCheck,
  type DoctorMode,
  type DoctorOptions,
  type DoctorReport,
  type DoctorStatus,
} from "./cli/index.js";

// Identity (DACS-1): cross-context identity resolution + claim helpers. Pure —
// no substrate import — so verifiers can parse/inspect CCI records too.
export {
  parseCciRecord,
  parseClaimRef,
  cciClaimRefs,
  cciHasClaim,
  identityBundleHash,
  type CciRecord,
  type CciClaim,
  type CciClaimKind,
  type CciWeb2Claim,
  type CciWalletClaim,
  type ParsedClaimRef,
} from "./identity/index.js";

// Discovery (§6.3.4 (b)/(c), #54): the PUBLISHED logical→native anchor binding.
// On Demos the native address folds in the writer's nonce, so it isn't
// recomputable — consumers resolve through this binding, never by program name
// (which the spec defines as an opaque write input, not a resolution key). Pure
// and substrate-neutral: the same surface serves an in-memory index, a
// `/.well-known` listings index (§6.3.5), or a catalog API (§6.3.6).
export {
  resolveBinding,
  resolveLatestVersion,
  createInMemoryBindingIndex,
  resolveAndRead,
  classifyAnchor,
  scanAnchorPage,
  scanAllAnchors,
  type AnchorBinding,
  type BindingResolution,
  type BindingIndex,
  type VerifiedRead,
  type VerifiedReadDeps,
  type AnchorKind,
  type RawAnchorEntry,
  type RawScanPage,
  type ScannedAnchor,
  type ScanPage,
  type ScanOptions,
} from "./discovery/index.js";

// Deterministic identityTier derivation (DACS-1 §6.3.2.1, IT-1..IT-3).
export {
  deriveIdentityTier,
  claimScheme,
  claimHasStructuralProof,
  TIER1_SCHEMES,
  type IdentityTier,
  type IdentityBundleLike,
  type BundleClaimLike,
  type BundleClaimVerifiedBy,
} from "./identity/tier.js";

// Negotiate (DACS-3): the sealed-envelope (sealed-bid) core — commitment/reveal
// crypto, deadline gating, and winner selection. Pure — no substrate import.
export {
  computeBidHash,
  generateSalt,
  saltHasEnoughEntropy,
  makeCommitment,
  verifyReveal,
  validateSealedParams,
  commitsInWindow,
  revealsInWindow,
  matchRevealsToCommits,
  parseRuleRef,
  verifyRuleRefContent,
  compareDecimal,
  selectSealedWinner,
  SEALED_BID_HASH_TAG,
  MIN_SALT_BYTES,
  MIN_COMMIT_LEAD_MS,
  MIN_REVEAL_WINDOW_SECONDS,
  type SealedBid,
  type AnchoredCommit,
  type AnchoredReveal,
  type SelectionRule,
  type SealedCommitment,
  type SealedEnvelopeParams,
  type SelectionOptions,
  type SelectionResult,
  type RuleRef,
  buildCommitMessage,
  buildRevealMessage,
  buildSealedAgreement,
  runSealedEnvelopeCore,
  type SealedChannelMessage,
  type SealedWinnerContext,
  type SealedAgreementContext,
  type SealedEnvelopeDeps,
  type SealedEnvelopeInput,
  type SealedEnvelopeResult,
} from "./negotiate/index.js";

// Public agent API (T4) — the headline surface a dApp dev uses.
export {
  createAgent,
  type Agent,
  type AgentConfig,
  type PublishResult,
  type DiscoveredListing,
  type BundleVerification,
  type SignatureCheck,
  verifyBundleCore,
  type VerifyBundleDeps,
  type SignatureVerdict,
  type RefCheck,
  type RefVerdict,
  bundleConsistency,
  bundlesDiverge,
  type ConsistencyVerdict,
  type BundleCopies,
  type BundleConsistencyDeps,
  type BundleRole,
  verifySettlementEvidence,
  type EvidenceDecision,
  type EvidenceVerification,
  type EvidenceContext,
  type EvidenceAgreementContext,
  type EvidenceRailContext,
  type EvidenceDeps,
  verifyBundleCopy,
  ABORT_OUTCOMES,
  type BundleCopyDeps,
  type BundleCopyRole,
  type CopyValidity,
  computeReputation,
  deriveReputation,
  type ReputationDerivation,
  type ReputationMetrics,
  type ReputationWindow,
  type SessionOutcome,
  type DeriveReputationDeps,
  discoverListings,
  validateListingArtifact,
  isVerifiedListingAdmission,
  checkListingRevocation,
  resolveListingPayloadVerificationCapability,
  resolveListingRails,
  assessListingReachability,
  type ListingValidationDisposition,
  type ListingValidationResult,
  type VerifiedListingAdmission,
  type ListingValidationDeps,
  type PayloadVerificationCapabilityDecision,
  type PayloadVerificationCapabilityInput,
  type PayloadVerificationCapabilityResolver,
  type ListingPayloadVerificationCapability,
  type RevocationCheck,
  type RevocationCheckResult,
  type RevocationSurface,
  type ListingRevocationDeps,
  type ListingRailResolution,
  type ListingRailResolutionResult,
  type ListingRailResolutionInput,
  type ListingRailAuthorityInput,
  type ListingPayPhaseClaim,
  type RailRegistryEntry,
  type ListingRailDefinition,
  type RailDefinitionProof,
  type SignatureVerifier,
  type ListingReachability,
  type ListingReachabilityDeps,
  type ListingReachabilityResult,
  type ReachabilityProbeResult,
  vetCore,
  type VetDeps,
  type VetRequest,
  type VetProxyResult,
  // DACS-2 §7.4.1 ParserSpec — signed recipe content rules (#49) + the engine seam.
  evaluateParserSpec,
  defaultParserEngine,
  type ParserSpec,
  type ParserFormat,
  type IndeterminatePredicate,
  type ParserEngine,
  type ParserEvalContext,
  type ParserEvaluation,
  type Reputation,
  // Injectable buyer-session core (F1 #14): run the lifecycle against any
  // SubstrateAdapter (mock/simulation/non-Demos). NOTE: `sessionAnchorName` is
  // deliberately NOT exported — its current MVP address strings are not the
  // normative §6.3.x schemes (dacs2:composite:{jobId}:{evaluatedParty},
  // dacs4:payment:{jobId}:{railId}:{phaseIndex}, role-specific bundle addr), and
  // freezing them into the public API would mislead third-party verifiers.
  // It stays internal until canonical addressing lands (tracked with #5/#48).
  runSessionCore,
  type SessionDeps,
  type RunSessionOptions,
  type SessionResult,
  type SessionTerms,
  type SettleRequest,
  type SettleResult,
  // Durable session store / checkpoint API (#55) — restart-safe orchestration.
  assertCheckpointPayloadShape,
  createInMemorySessionStore,
  SESSION_STORE_VERSION,
  type SessionStore,
  type SessionRecord,
  type SessionReceipt,
  type SessionCheckpoint,
  type CheckpointValue,
  type SessionLease,
  type SessionPhase,
  type SessionLoad,
  type TransitionInput,
  type TransitionResult,
  createFsSessionStore,
  type FsSessionStoreOptions,
  buildTwoSidedBundle,
  bundleSignedScope,
  attestationBundleHash,
  BUNDLE_SIGNED_SCOPE_OMIT,
  BUNDLE_OUTCOMES,
  type BundleOutcome,
  type BundleAnchorRole,
  type SessionParty,
  type SigningSessionParty,
  type TwoSidedSession,
  type TwoSidedBundles,
  buildSignedArtifact,
  verifySignedArtifact,
  type SignedArtifact,
  type Signer,
  type Verifier,
} from "./agent/index.js";

// Settlement rails (SR-4): x402 reference rail + the runSession `settle` bridge.
export {
  createX402Rail,
  x402Settle,
  x402SettleCore,
  termsMatch,
  type X402Rail,
  type X402RailConfig,
  type X402SettleParams,
  type X402SettleCoreDeps,
  type X402ClientLike,
  type X402PaymentRequired,
  type X402PaymentRequirement,
  createEvmErc20Rail,
  evmErc20Settle,
  evmErc20SettleCore,
  createIdempotencyStore,
  createInMemorySettlementLog,
  settlementKey,
  type SettlementIdempotencyStore,
  type SettlementLog,
  type SettlementReconcile,
  type EvmErc20Rail,
  type EvmErc20RailConfig,
  type EvmErc20SettleParams,
  type EvmTransferClient,
  createPayD402Rail,
  payD402Settle,
  payD402SettleCore,
  termsMatchD402,
  PAY_D402_AVAILABILITY,
  type PayD402Rail,
  type PayD402RailConfig,
  type PayD402SettleParams,
  type PayD402SettleCoreDeps,
  type D402ClientLike,
  type D402PaymentRequirement,
  type D402SettlementResult,
  createPayDemRail,
  payDemSettle,
  payDemSettleCore,
  type PayDemRail,
  type PayDemRailConfig,
  type PayDemSettleParams,
  type DemosNativeClient,
  type DemosTransferResult,
} from "./rails/index.js";

// Transport-independent seller intake (DACS-3 §8.5/§8.6; DACS-4
// §9.5.1/§9.5.7..§9.5.9). Pure verification only: no server, transport,
// payment submission, or application callback is coupled to this surface.
export {
  verifyX402ReceiptClaim,
  X402_V1_CHAIN_IDS,
  verifySellerPaymentIntake,
  canonicalSellerSettlementId,
  createInMemorySellerReceiptStore,
  x402Eip3009Nonce,
  type X402ReceiptDisposition,
  type X402ResponseHeader,
  type X402ReceiptEvidence,
  type X402ReceiptVerification,
  type SellerPaymentIntakeDisposition,
  type SellerFulfilmentPermit,
  type SellerSessionBindingGuarantee,
  type SellerDemosTxRef,
  type SellerX402TxRef,
  type SellerPaymentTxRef,
  type SellerPaymentFinality,
  type SellerPaymentEvidenceInput,
  type SellerPaymentClaim,
  type SellerPaymentIntakeInput,
  type CommittedAgreementResolution,
  type IdentityBundleResolution,
  type SellerDemosRailDefinition,
  type SellerX402RailDefinition,
  type SellerSupportedRailDefinition,
  type SellerRailResolution,
  type AddressResolution,
  type DestinationBindingResolution,
  type DemosTransferObservation,
  type X402SessionBinding,
  type X402TransferObservation,
  type SellerReceiptClaim,
  type SellerReceiptClaimResult,
  type SellerReceiptStore,
  type SellerPaymentIntakeDeps,
  type SellerPaymentIntakeResult,
} from "./seller/index.js";

// Steward registries (T12/T13): resolve + pin steward-signed rails/recipes,
// dispatch the money path by rail kind.
export {
  resolveRail,
  resolveRecipe,
  type RegistryResolveDeps,
  settleFromRail,
  type RailDispatchOptions,
  type Availability,
  type RailDescriptor,
  type RecipeDescriptor,
  type Registry,
} from "./registry/index.js";

// Artifact model (T3): spine artifact types, kind→separator registry, validators.
export {
  type ArtifactKind,
  type ClaimRef,
  type ClaimRequirement,
  type VerifyResultRef,
  type BundleClaim,
  type PresentationSignature,
  type IdentityBundle,
  type BundleRequirement,
  type Price,
  type Delivery,
  type Listing,
  type ListingEnvelope,
  type ListingSignature,
  type RevocationMarker,
  type RevocationBinding,
  type ListingDraft,
  type LegacyMvpListing,
  type ReadableListing,
  type ListingPin,
  type ListingTerms,
  type SubstrateRequirement,
  type PhaseType,
  type PhaseStep,
  type VerificationMethod,
  type DeliverableSpec,
  type DeliverableRef,
  type PaymentRailRef,
  type PriceTerm,
  type PricingSpec,
  type ClaimProofRef,
  type VerifyResultEntry,
  type CompositeVerificationRecord,
  type AgreementDocument,
  type AgreementParty,
  type AgreementSignature,
  type AgreementTerms,
  type PayoutBinding,
  type PriceAnchor,
  type FeeRecurrencePeriod,
  type FeeItem,
  type FeeSchedule,
  type PayeeBoundAgreementTerms,
  type PayeeBoundAgreementDocument,
  type AgreementArtifact,
  type AttestationAnchorKind,
  type AttestationAnchor,
  type AttestationRef,
  type ListingRef,
  type ChainTxRef,
  type TxRef,
  type PaymentAmount,
  type SettlementFinality,
  type ComponentSignatureAlgorithm,
  type ComponentSignature,
  type CommitmentRecord,
  type FinalityCommitmentRecord,
  type AgreementCommitmentRecord,
  type AnchorTransactionRef,
  type AnchorReceiptEvidence,
  type AnchorLifecycleState,
  type AnchorReceipt,
  type ArtifactSignature,
  type PaymentPhaseType,
  type DeliveryPhaseType,
  type SettlementEvidence,
  type Rating,
  type BundleParty,
  type PhaseSummaryEntry,
  type LegacyBundlePhaseEntry,
  type BundlePhaseOutcome,
  type BundlePhaseErrorClass,
  type BundleSignature,
  type AttestationBundle,
  type FaultAttestationBundle,
  type AnyAttestationBundle,
  type BundlePartyRole,
  type FaultedParty,
  type LegacyMvpAttestationRef,
  type LegacyMvpAgreementDocument,
  type LegacyMvpTxRef,
  type LegacyMvpSettlementEvidence,
  type LegacyMvpPhaseSummaryEntry,
  type LegacyMvpAttestationBundle,
  type LegacyMvpFaultAttestationBundle,
  type LegacyMvpAnyAttestationBundle,
  ARTIFACT_SEPARATORS,
  RATING_SEPARATOR,
  separatorFor,
  isListing,
  isListingEnvelope,
  isListingPipelineValid,
  isPaymentRailRef,
  isRevocationMarker,
  isRevocationBinding,
  isListingDraft,
  isLegacyMvpListing,
  readListingArtifact,
  isListingPublicEndpoint,
  isIdentityBundle,
  isBundleRequirement,
  isVerificationMethod,
  isDeliverableSpec,
  isPhaseStep,
  isListingTerms,
  isPricingSpec,
  isCompositeVerificationRecord,
  isAgreementDocument,
  isPayeeBoundAgreementDocument,
  isAgreementArtifact,
  isCommitmentRecord,
  isFinalityCommitmentRecord,
  isAgreementCommitmentRecord,
  isAnchorReceipt,
  isAttestationRef,
  isChainTxRef,
  isSettlementEvidence,
  isAttestationBundle,
  isFaultAttestationBundle,
  isAnyAttestationBundle,
  isLegacyMvpAttestationRef,
  isLegacyMvpAgreementDocument,
  isLegacyMvpTxRef,
  isLegacyMvpSettlementEvidence,
  isLegacyMvpAttestationBundle,
  isLegacyMvpFaultAttestationBundle,
  isLegacyMvpAnyAttestationBundle,
  COMPONENT_SIGNATURE_ALGORITHMS,
  isCanonicalBase64Url,
  isComponentSignature,
  buildComponentSignature,
  signComponentArtifact,
  verifyComponentSignature,
  type ComponentSignedArtifact,
  type ComponentSigner,
  type BuildComponentSignatureOptions,
  type ComponentSignatureStatus,
  type ComponentSignatureMalformedReason,
  type ComponentSignatureUnresolvedReason,
  type ComponentSignatureInvalidReason,
  type ComponentSignatureVerification,
  type VerifyComponentSignatureInput,
  type VerifyComponentSignatureDeps,
} from "./artifacts/index.js";
