/**
 * dacs-sdk — reusable runtime for building DACS (Demos Agent Commerce
 * Standards) agents across the Identify → Vet → Negotiate → Settle → Verify
 * lifecycle.
 *
 * T1 scaffold: this exports the substrate seam (SubstrateAdapter + DemosAdapter)
 * and package metadata. The agent-facing public API (`createAgent`,
 * `publishListing`, `readListing`, `enumerateListings`, `discover`,
 * `runSession`, `verifyBundle`, `getReputation`) is designed in T4 — see
 * IMPLEMENTATION.md.
 */

export { VERSION, DACS_MVP_TARGET, DACS_STANDARD_PIN } from "./version.js";
export { isDacsPublicAddressV1 } from "./agent/publicAddress.js";
export * from "./commerce/index.js";
export {
  admitChannelMessage,
  prepareChannelMessageSigningInput,
  type ChannelMessageType,
  type ChannelMessage,
  type ChannelAdmissionContext,
  type UnsignedChannelMessage,
  type ChannelMessageSigningInput,
  type ChannelMessageSignatureVerificationInput,
  type ChannelMessageSignatureVerifier,
  type ChannelMessageAdmissionFailure,
  type ChannelMessageAdmissionResult,
} from "./negotiate/channel.js";
export {
  deriveRfqPriceBand,
  validateRfqProposal,
  openRfqSession,
  advanceRfqSession,
  rfqSessionCheckpointHash,
  type RfqPriceBand,
  type RfqPricing,
  type RfqPartyInput,
  type RfqProposal,
  type RfqProposalBody,
  type RfqAcceptBody,
  type RfqTerminalBody,
  type RfqTurnBody,
  type RfqSessionPartyBinding,
  type RfqSessionStatus,
  type RfqStandingProposal,
  type RfqSessionState,
  type OpenRfqSessionInput,
  type RfqChannelReservationInput,
  type RfqChannelReservation,
  type OpenRfqSessionResult,
  type AdvanceRfqSessionResult,
} from "./negotiate/rfq.js";
export {
  deriveRfqAgreement,
  signRfqAgreement,
  type RfqAgreementInput,
} from "./negotiate/rfqAgreement.js";
export {
  prepareRfqTranscript,
  planRfqTranscriptDisclosure,
  type VerifiedRfqTranscript,
  type PrepareRfqTranscriptInput,
  type RfqTranscriptConsentInput,
  type RfqTranscriptConsentVerificationInput,
  type RfqTranscriptConsentVerifier,
  type RfqTranscriptDisclosureAction,
  type RfqTranscriptDisclosureResult,
  type PlanRfqTranscriptDisclosureInput,
} from "./negotiate/rfqTranscript.js";
export {
  FINALITY_COMMITMENT_SEPARATOR,
  LEGACY_COMMITMENT_SEPARATOR,
  finalityCommitmentAddress,
  commitFixedPriceAgreement,
  commitRfqAgreement,
  readLegacyFixedPriceAgreementCommitment,
  validateFixedPriceAgreementBinding,
  validateRfqAgreementBinding,
  type CommitmentVerificationDisposition,
  type CommitmentSignatureVerificationInput,
  type CommitmentSignatureVerifier,
  type AnchoredFinalityCommitment,
  type AnchoredLegacyCommitment,
  type AnchoredAgreementCommitment,
  type FinalityCommitmentLookup,
  type FinalityCommitmentReader,
  type FinalityCommitmentProvider,
  type CommitmentSessionPartyBinding,
  type CommitmentSessionBinding,
  type CommitAgreementInput,
  type CommitFixedPriceAgreementInput,
  type CommitRfqAgreementInput,
  type ReadLegacyFixedPriceAgreementCommitmentInput,
  type FinalizedFinalityAgreementCommitment,
  type FinalizedLegacyAgreementCommitment,
  type FinalizedAgreementCommitment,
} from "./negotiate/commitment.js";
export {
  ceilMeteredQuantity,
  deriveMeteredPriceTerm,
  negotiablePriceBand,
  isNegotiablePriceWithinBand,
  deriveFixedPriceAgreement,
  signAgreementArtifact,
  signFixedPriceAgreement,
  type VerifiedListingInput,
  type FixedPricePartyInput,
  type FixedPriceAgreementInput,
  type MeteredQuantityInput,
  type NegotiablePriceBand,
  type UnsignedAgreementArtifact,
  type AgreementSigner,
} from "./negotiate/fixedPrice.js";
export {
  isCanonicalJobId,
  requireCanonicalJobId,
  generateCanonicalJobId,
  type GenerateCanonicalJobIdOptions,
} from "./negotiate/jobId.js";
export {
  createFixedPriceAgreementSigningPlan,
  fixedPriceAgreementSignedBytes,
  createFixedPriceAgreementSignatureContribution,
  finalizeFixedPriceAgreementContributions,
  type FixedPriceAgreementSigningRole,
  type FixedPriceAgreementRequiredSigner,
  type FixedPriceAgreementSigningPlan,
  type FixedPriceAgreementSignatureContribution,
  type FixedPriceAgreementContributionVerificationDisposition,
  type FixedPriceAgreementContributionVerificationInput,
  type FixedPriceAgreementContributionVerifier,
} from "./negotiate/fixedPriceExchange.js";
export {
  advanceFixedPriceAgreementDurable,
  fixedPriceAgreementLogicalAddress,
  durableFixedPriceAgreementCheckpointKey,
  type FixedPriceAgreementEffectFence,
  type DurableFixedPriceAgreementSigner,
  type DurableFixedPriceAgreementInput,
  type FixedPriceAgreementTransportIdentity,
  type FixedPriceAgreementProposal,
  type FixedPriceAgreementResolution,
  type FixedPriceAgreementEffectSubmission,
  type FixedPriceAgreementSignatureReconciliation,
  type FixedPriceAgreementTransport,
  type AnchoredFixedPriceAgreementReadback,
  type FixedPriceAgreementAnchorVerificationDisposition,
  type FixedPriceAgreementAnchorProvider,
  type DurableFixedPriceAgreementDurability,
  type DurableAnchoredFixedPriceAgreement,
  type DurableFixedPriceAgreementStage,
  type DurableFixedPriceAgreementProgress,
} from "./negotiate/durableFixedPriceExchange.js";

export {
  DacsError,
  NotImplementedError,
  TransientError,
  CounterpartyError,
  SubstrateError,
  UnsupportedCapabilityError,
  faultCategory,
  type FaultCategory,
} from "./errors.js";

// Shared host-local durability boundary used by every filesystem-backed store
// (including the companion dacs-node package).
export {
  preparePrivateStoreDirectory,
  readPrivateFile,
  atomicWritePrivateFile,
  exclusiveWritePrivateFile,
  isPathWithinPrivateRoot,
} from "./filesystem/privateStore.js";

// Foundation (T2): canonical form, decimals, content hashing, domain-separated signing.
export {
  canonicalize,
  canonicalizeDecimal,
  assertPositiveAmount,
  baseUnits,
  encodeAddressSegment,
  decodeAddressSegment,
  listingAddress,
  attestationAddress,
  paymentEvidenceAddress,
  ratingAddress,
  logicalToStorageProgramName,
  storAddress,
  bundleAddress,
  sha256Hex,
  stripSignature,
  canonicalSignedScope,
  contentHash,
} from "./canonical/index.js";
export {
  privateKeyFromSeed,
  publicKeyFromSeed,
  publicKeyFromRaw,
  rawPublicKey,
  ed25519Sign,
  ed25519Verify,
  SIGNATURE_DOMAIN_SEPARATORS,
  type DomainSeparator,
  COMPOSITE_DOMAIN_SEPARATORS,
  type CompositeDomainSeparator,
  isRegisteredSeparator,
  isCompositeSeparator,
  dacsXSeparator,
  signedBytes,
  signArtifact,
  verifyArtifact,
  sessionBindingBytes,
  signSessionBinding,
  verifySessionBinding,
  autoAcceptInstanceBytes,
  signAutoAcceptInstance,
  verifyAutoAcceptInstance,
} from "./crypto/index.js";

// Types only — the `DemosAdapter` *value* lives on the
// "@kynesyslabs/dacs/substrate" subpath so this top-level barrel stays free of
// an eager @kynesyslabs/demosdk load (its ESM packaging breaks plain-Node-ESM
// consumers of the pure/verify surface). createAgent lazy-loads it when needed.
export type {
  DemosAdapterConfig,
  DemosWriteEvidence,
  SubstrateAdapter,
  AnchorAttemptReceipt,
  AnchorAttempts,
  AnchorCompletion,
  AnchorRef,
  AnchorState,
  AnchorTimings,
  AnchorWaitFailureCode,
  AnchorWaitOptions,
  AnchorWriteOnceOptions,
  ProxyFetchRequest,
  ProxyFetchResult,
  ResolvedIdentity,
  AnchorReceipt as SubstrateAnchorReceipt,
} from "./substrate/SubstrateAdapter.js";
export type {
  DemosWriteJournal,
  DemosWriteJournalKey,
  DemosWriteJournalRecord,
  DemosWriteJournalSnapshot,
} from "./substrate/demosWriteJournal.js";
export {
  createInMemoryDemosWriteJournal,
} from "./substrate/demosWriteJournal.js";
export {
  createFsDemosWriteJournal,
  type FsDemosWriteJournalOptions,
} from "./substrate/demosWriteJournalFs.js";
export {
  assertDemosWriteEvidence,
  decodeDemosAnchorReceiptProof,
  demosSignedTransactionProofHash,
  demosWriteEvidenceBindsReceiptContent,
  demosWriteEvidenceToAnchorReceipt,
  type DemosAnchorReceiptProof,
  type DemosPortableAnchorReceiptInput,
} from "./substrate/demosWriteEvidence.js";
// Pure error value: exporting this directly does not eagerly load demosdk.
export { AnchorWaitError } from "./substrate/AnchorWaitError.js";
export {
  createDemosHistoryPageFetcher,
  DEMOS_HISTORY_MAX_PAGE_SIZE,
  type DemosHistoryClient,
} from "./substrate/demosHistory.js";

// CLI helpers (pure/read-only by default). The executable entry is `dacs`.
export {
  formatDoctorText,
  redactRpcUrl,
  redactSecret,
  runDoctor,
  sanitizeText,
  type DoctorAdapter,
  type DoctorCheck,
  type DoctorMode,
  type DoctorOptions,
  type DoctorReport,
  type DoctorStatus,
} from "./cli/index.js";

// Identity (DACS-1): cross-context identity resolution + claim helpers. Pure —
// no substrate import — so verifiers can parse/inspect CCI records too.
export {
  DEMOS_CCI_RESPONSE_LIMITS,
  assertDemosCciResponseBounds,
  parseCciRecord,
  parseClaimRef,
  cciClaimRefs,
  cciHasClaim,
  cciClaimProof,
  cciClaimHasProof,
  authenticateDemosCciRecord,
  canonicalDemosAgentPublicKey,
  classifyCciTlsnProof,
  demosAgentClaimRef,
  demosAgentPublicKey,
  getAuthenticatedCciProvenance,
  isAuthenticatedCciRecord,
  projectCciSupplementarySignals,
  identityBundleHash,
  siwdBundleResource,
  siwdResourcesBindBundleHash,
  isCanonicalClaimReference,
  isDemosAgentClaimRef,
  parseCanonicalClaimReference,
  parseDemosAgentClaimReference,
  requireCanonicalClaimReference,
  sameCanonicalClaimIdentity,
  canonicalizeNativeDomainHostname,
  domainClaimReferenceFromNativeHostname,
  isCanonicalDomainHostname,
  readAuthenticatedDomainClaims,
  verifyDemosGcrDomainClaims,
  type AuthenticatedDomainArtifactDeps,
  type AuthenticatedDomainClaimRead,
  type CanonicalClaimIdentity,
  type CanonicalClaimReferenceParts,
  type ClaimReferenceSchemeStatus,
  type ParsedDemosAgentClaimReference,
  type CciRecord,
  type CciClaim,
  type CciClaimKind,
  type CciWeb2Claim,
  type CciWalletClaim,
  type CciUdClaim,
  type CciPqcClaim,
  type CciNomisClaim,
  type CciHumanPassportClaim,
  type CciEthosClaim,
  type CciTlsnClaim,
  type AuthenticateDemosCciDeps,
  type AuthenticateDemosCciInput,
  type AuthenticateDemosCciProviderClaimInput,
  type AuthenticateDemosCciResult,
  type AuthenticatedCciRecord,
  type CciSignalOmission,
  type CciSignalOmissionReason,
  type CciSupplementaryFreshnessPolicy,
  type CciSupplementarySignalProjection,
  type CciTlsnDisposition,
  type CciTlsnSessionContext,
  type ClassifyCciTlsnDeps,
  type DemosCciProvenance,
  type DemosCciProviderClaim,
  type DemosCciProviderClaimAuthentication,
  type DemosCciResolutionAuthentication,
  type NativeCciTlsnBinding,
  type NativeCciTlsnAuthentication,
  type VerifyNativeCciTlsnInput,
  type ParsedClaimRef,
  type DemosGcrDomainMetadata,
  type DemosGcrDomainVerification,
  type DemosGcrResolution,
  type DomainArtifactAuthentication,
  type DomainArtifactProfile,
  type DomainClaimArtifactLike,
  type DomainClaimDiagnostic,
  type ReportedDemosGcrResultTimes,
  type VerifyDemosGcrDomainDeps,
} from "./identity/index.js";

// Discovery (§6.3.4 (b)/(c), #54): the PUBLISHED logical→native anchor binding.
// On Demos the native address folds in the writer's nonce, so it isn't
// recomputable — consumers resolve through this binding, never by program name
// (which the spec defines as an opaque write input, not a resolution key). Pure
// and substrate-neutral: the same surface serves an in-memory index, a
// `/.well-known` listings index (§6.3.5), or a catalog API (§6.3.6).
export {
  resolveBinding,
  resolveLatestVersion,
  createInMemoryBindingIndex,
  createInMemoryBindingStore,
  queryListingCatalog,
  createCatalogBindingIndex,
  createBoundArtifactRepository,
  resolveAndRead,
  classifyAnchor,
  scanAnchorPage,
  scanAllAnchors,
  type AnchorBinding,
  type BindingResolution,
  type BindingIndex,
  type BindingPublication,
  type BindingPublisher,
  type BindingStore,
  type CatalogReachabilityHint,
  type CatalogReputationHint,
  type CatalogListingSummary,
  type ListingCatalogQuery,
  type ListingCatalogPage,
  type ListingCatalogQueryResult,
  type ListingCatalogClientConfig,
  type ListingCatalogRequestOptions,
  type CatalogBindingIndexConfig,
  type BoundArtifactAdapter,
  type BoundArtifactRepository,
  type BoundArtifactRepositoryDeps,
  type BoundArtifactWriteOptions,
  type BoundArtifactWriteResult,
  type VerifiedRead,
  type VerifiedReadDeps,
  type AnchorKind,
  type AnchorHistoryPageFetcher,
  type RawAnchorEntry,
  type RawScanPage,
  type ScannedAnchor,
  type ScanPage,
  type ScanOptions,
  type ScanSeen,
} from "./discovery/index.js";

// Deterministic identityTier derivation (DACS-1 §6.3.2.1, IT-1..IT-3).
export {
  deriveIdentityTier,
  claimScheme,
  claimHasStructuralProof,
  TIER1_SCHEMES,
  type IdentityTier,
  type IdentityBundleLike,
  type BundleClaimLike,
  type BundleClaimVerifiedBy,
} from "./identity/tier.js";

// Negotiate (DACS-3): the sealed-envelope (sealed-bid) core — commitment/reveal
// crypto, deadline gating, and winner selection. Pure — no substrate import.
export {
  computeBidHash,
  generateSalt,
  saltHasEnoughEntropy,
  makeCommitment,
  verifyReveal,
  validateSealedParams,
  commitsInWindow,
  resolveCommitWindow,
  revealsInWindow,
  matchRevealsToCommits,
  parseRuleRef,
  verifyRuleRefContent,
  compareDecimal,
  selectSealedWinner,
  SEALED_BID_HASH_TAG,
  MIN_SALT_BYTES,
  MIN_COMMIT_LEAD_MS,
  MIN_REVEAL_WINDOW_SECONDS,
  type SealedBid,
  type AnchoredCommit,
  type ResolvedAnchoredCommit,
  type AnchoredReveal,
  type SelectionRule,
  type SealedCommitment,
  type SealedEnvelopeBaseParams,
  type DemandSealedEnvelopeParams,
  type ProcurementSealedEnvelopeParams,
  type SealedEnvelopeParams,
  type CommitWindowResolution,
  type SelectionOptions,
  type SelectionResult,
  type RuleRef,
  buildCommitMessage,
  buildRevealMessage,
  buildSealedAgreement,
  resolveSealedEnvelopeMode,
  assignSealedEnvelopeRoles,
  validateSealedAgreementRoleAssignment,
  validateSealedAgreementForCommit,
  runSealedEnvelopeCore,
  DEMAND_SEALED_ENVELOPE_PHASE,
  PROCUREMENT_SEALED_ENVELOPE_PHASE,
  type SealedChannelMessage,
  type SealedEnvelopePhaseKind,
  type SealedEnvelopeAuctionMode,
  type SealedEnvelopeModeResolution,
  type SealedAgreementParty,
  type SealedAgreementRoleAssignment,
  type SealedAgreementRoleValidation,
  type SealedAgreementCommitValidation,
  type SealedAgreementCommitResult,
  type VerifiedSealedAgreementCommitResult,
  type LegacySealedAgreementCommitResult,
  type SealedCommitContext,
  type SealedWinnerContext,
  type SealedAgreementContext,
  type SealedEnvelopeDeps,
  type SealedEnvelopeInput,
  type SealedEnvelopeResult,
  type VerifiedSelectionRule,
  type SealedRuleEvaluationInput,
} from "./negotiate/index.js";

// Public agent API (T4) — the headline surface a dApp dev uses.
export {
  createAgent,
  createUnsafeManualAgent,
  type Agent,
  type UnsafeManualAgent,
  type AgentConfig,
  type AgentDemosCciConfig,
  type AgentNativeCciTlsnInput,
  type AgentSettlementEvidenceContext,
  type AgentSettlementEvidenceContextInput,
  type AgentSettlementEvidenceContextResolver,
  type DemosBackedAdapter,
  type AgentBindingConfig,
  type PublishResult,
  type DiscoveredListing,
  type AuthenticatedListing,
  type EnumerateListingsOptions,
  type ListingEnumerationDiagnostic,
  type ListingEnumerationResult,
  type ListingReadFailure,
  type ListingReadRejectionCheck,
  type ListingReadRejectionCode,
  type ListingReadResult,
  type SessionListingInput,
  type BundleVerification,
  type SignatureCheck,
  verifyBundleCore,
  type VerifyBundleDeps,
  type SignatureVerdict,
  type RefCheck,
  type RefVerdict,
  type BundleEvidenceVerificationContext,
  type BundleEvidenceVerificationResult,
  type AlternativePaymentBundleVerificationInput,
  type AlternativePaymentBundleVerificationResult,
  bundleConsistency,
  lookupBundleCopies,
  bundlesDiverge,
  type ConsistencyVerdict,
  type BundleCopyRead,
  type BundleCopyReader,
  type BundleCopies,
  type BundleConsistencyDeps,
  type BundleRole,
  verifySettlementEvidence,
  validateSettlementEvidenceStructure,
  type EvidenceDecision,
  type EvidenceVerification,
  type EvidenceStructureDecision,
  type EvidenceStructureValidation,
  type EvidenceContext,
  type AuthenticatedEvidenceContext,
  type EvidenceAgreementContext,
  type EvidenceRailContext,
  type EvidenceRailAssetSpecContext,
  type EvidenceRailNetworkSpecContext,
  type EvidenceDeps,
  type AuthenticatedEvidenceDeps,
  verifyBundleCopy,
  ABORT_OUTCOMES,
  type BundleCopyDeps,
  type BundleCopyRole,
  type CopyValidity,
  computeReputation,
  deriveReputation,
  deriveReputationWithValidation,
  type ReputationDerivation,
  type ReputationMetrics,
  type ReputationWindow,
  type SessionOutcome,
  type DeriveReputationDeps,
  type DeriveReputationValidationDeps,
  isDacs5SessionTransitionAllowed,
  dacs5BundleOutcomeForTerminalState,
  type Dacs5SessionState,
  type Dacs5ResumableSessionState,
  type Dacs5SessionTransitionContext,
  classifyVerificationDecision,
  isVerifyResultForMethod,
  shouldRetryVerification,
  vetPhaseFailureClass,
  type VerificationRetryPolicy,
  type VetPhaseFailureCause,
  type VetPhaseFailureClass,
  discoverListings,
  validateListingArtifact,
  isVerifiedListingAdmission,
  checkListingRevocation,
  resolveListingPayloadVerificationCapability,
  resolveListingRails,
  assessListingReachability,
  type ListingValidationDisposition,
  type ListingValidationResult,
  type VerifiedListingAdmission,
  type ListingValidationDeps,
  type PayloadVerificationCapabilityDecision,
  type PayloadVerificationCapabilityInput,
  type PayloadVerificationCapabilityResolver,
  type ListingPayloadVerificationCapability,
  type RevocationCheck,
  type RevocationCheckResult,
  type RevocationSurface,
  type ListingRevocationDeps,
  type ListingRailResolution,
  type ListingRailResolutionResult,
  type ListingRailResolutionInput,
  type ListingRailAuthorityInput,
  type ListingPayPhaseClaim,
  type RailRegistryEntry,
  type ListingRailDefinition,
  type RailDefinitionProof,
  type SignatureVerifier,
  type ListingReachability,
  type ListingReachabilityDeps,
  type ListingReachabilityResult,
  type ReachabilityProbeResult,
  vetCore,
  partyVetCore,
  SELF_SIGNED_ASSERTION_SEPARATOR,
  selfSignedAssertionBytes,
  selfSignedAssertionAddress,
  compositeVerificationAddress,
  isFinalizedVetAnchorReceipt,
  type VetDeps,
  type VetRequest,
  type PartyVetRequest,
  type PartyVetAttemptRequest,
  type PartyVetDeps,
  type PartyVetOperationCheckpoint,
  type PartyVetOperationStore,
  type PartyVetEffectAuthorizationVerdict,
  type PartyVetAuthorizedRunResult,
  type VetProxyResult,
  type VetProduction,
  type VetMethodOutcome,
  type VetOperationCheckpoint,
  type VetOperationStore,
  type FinalizedVetAnchor,
  type FinalizedVetAnchorReceipt,
  type SelfSignedMethodInput,
  type SelfSignedAttestationArtifact,
  type SelfSignedAnchorInput,
  partyVetCompositeAddress,
  partyVetPinScopeHash,
  type PartyVetRequirementPath,
  type PartyVetMethodInput,
  type PartyVetRecipePinBinding,
  type PartyVetPinScopeAttemptInput,
  type PartyVetPinScopeInput,
  aggregateCompositeVerification,
  isCompositeBundleRequirement,
  verifyCompositeVerificationRecord,
  type CompositeClaimRequirement,
  type CompositeBundleRequirement,
  type ExpectedVerifyResult,
  type CompositeVerificationExpectations,
  type ResolvedVerificationContent,
  type AuthorityVerification,
  type VerifyAuthorityAttestationInput,
  type VerifyCompositeVerificationDeps,
  type CompositeVerificationInvalidCode,
  type CompositeVerificationUnresolvedCode,
  type StrictCompositeVerification,
  // DACS-2 §7.4.1 ParserSpec — signed recipe content rules (#49) + the engine seam.
  evaluateParserSpec,
  defaultParserEngine,
  defaultParserEngineCapabilities,
  type ParserSpec,
  type ParserFormat,
  type IndeterminatePredicate,
  type ParserEngine,
  type ParserEngineCapabilities,
  type ParserEvalContext,
  type ParserEvaluation,
  type Reputation,
  type ReputationExclusion,
  // Injectable legacy buyer-session core (F1 #14). Its historical address
  // grammar is public only under an explicit compatibility name; current
  // producers export their own typed normative address functions.
  runSessionCore,
  legacyMvpSessionAnchorName,
  type SessionDeps,
  type RunSessionOptions,
  type SessionResult,
  type SessionVetRequest,
  type VetFinalityAuthenticationRequest,
  type SessionTerms,
  type SettleRequest,
  type SettleResult,
  type SettlementRecoveryAttempt,
  // Legacy v1 session store API. Its public names and behaviour remain stable.
  assertCheckpointPayloadShape,
  createInMemorySessionStore,
  SESSION_STORE_VERSION,
  type SessionStore,
  type SessionRecord,
  type SessionReceipt,
  type SessionCheckpoint,
  type CheckpointValue,
  type SessionLease,
  type SessionPhase,
  type SessionLoad,
  type TransitionInput,
  type TransitionResult,
  createFsSessionStore,
  type FsSessionStoreOptions,
  // Generation-fenced v2 is a separate, explicit API; no v1 value is upgraded.
  FENCED_SESSION_STORE_VERSION,
  assertFencedCheckpointPayloadShape,
  assertFencedSessionPaymentAuthorizationShape,
  assertFencedSessionReceiptShape,
  createInMemoryFencedSessionStore,
  createFsFencedSessionStore,
  fencedSessionReceiptKey,
  sessionPhaseIsTerminal,
  terminalBundleStorePhase,
  type FencedSessionStoreV2,
  type FencedSessionRecordV2,
  type FencedSessionReceiptV2,
  type FencedSessionCheckpointV2,
  type FencedCheckpointValueV2,
  type FencedSessionLeaseV2,
  type FencedSessionLeaseTokenV2,
  type FencedSessionPaymentAuthorizationBindingV2,
  type FencedSessionPhaseV2,
  type FencedSessionLoadV2,
  type FencedMutationFailureReasonV2,
  type FencedCheckpointClaimInputV2,
  type FencedCheckpointClaimResultV2,
  type FencedLeaseResultV2,
  type FencedSessionAuthorizationBindingResultV2,
  type FencedTransitionInputV2,
  type FencedTransitionResultV2,
  type TerminalBundleStoreRole,
  type TerminalBundleStoreStage,
  type FsFencedSessionStoreOptions,
  SESSION_RECIPE_REGISTRY_SNAPSHOT_CHECKPOINT_KEY,
  pinSessionRecipeRegistrySnapshot,
  recoverSessionRecipeRegistrySnapshot,
  pinSessionRecipeSelection,
  recoverSessionRecipePin,
  isDurableSessionRecipeRegistrySnapshot,
  isDurableSessionRecipePin,
  type DurableRecipePartyIdentity,
  type DurableRecipeRequirementPath,
  type DurableRecipeSelectionProvenance,
  type DurableSessionRecipeRegistrySnapshot,
  type DurableSessionRecipePin,
  type PinSessionRecipeRegistrySnapshotInput,
  type RecoverSessionRecipeRegistrySnapshotInput,
  type PinSessionRecipeInput,
  type RecoverSessionRecipePinInput,
  buildTwoSidedBundle,
  bundleSignedScope,
  attestationBundleHash,
  BUNDLE_SIGNED_SCOPE_OMIT,
  BUNDLE_OUTCOMES,
  type BundleOutcome,
  type BundleAnchorRole,
  type SessionSigner,
  type SessionParty,
  type SigningSessionParty,
  type TwoSidedSession,
  type TwoSidedBundles,
  assembleTerminalBundleForOwnRole,
  createTerminalBundleAuthority,
  createTerminalBundlePlan,
  createTerminalBundleSignatureContribution,
  createTerminalBundleSignatureMatrix,
  terminalBundleAuthorityHash,
  terminalBundleSignedBytes,
  type TerminalAbortEligibility,
  type TerminalBundleAuthority,
  type TerminalBundleAuthorityInput,
  type TerminalBundleClass,
  type TerminalBundleContributionSignature,
  type TerminalBundleMatrixCopy,
  type TerminalBundleOwnRole,
  type TerminalBundlePlan,
  type TerminalBundleRequiredSigner,
  type TerminalBundleRolePlan,
  type TerminalBundleSignatureContribution,
  type TerminalBundleSignatureMatrix,
  type TerminalBundleSignatureValue,
  type TerminalBundleSignerPublicKey,
  type TerminalBundleSigningMode,
  type TerminalIrreversibleEffectObservation,
  type TerminalPhaseAuthority,
  type VerifiedTerminalBundleParty,
  prepareVetTerminalBundle,
  type PrepareVetTerminalBundleDeps,
  type PrepareVetTerminalBundleInput,
  type PreparedVetTerminalBundle,
  type VetFailureTerminalSessionRecord,
  type VetProductionAuthentication,
  type VetTerminalSessionParty,
  advanceTerminalBundleDurable,
  getTerminalBundleFinalizationStatus,
  terminalBundleFinalizationCheckpointKey,
  terminalBundleFinalizationCheckpointName,
  verifyFinalizedTerminalBundleReadOnly,
  type DurableFinalizedTerminalBundle,
  type DurableTerminalBundleInput,
  type DurableTerminalBundleProgress,
  type DurableTerminalBundleProvider,
  type TerminalBundleAnchorPublication,
  type TerminalBundleCheckpointState,
  type TerminalBundleEffectFence,
  type TerminalBundleFencedSigner,
  type TerminalBundleFinalizationDurability,
  type TerminalBundleFinalizationReadProvider,
  type TerminalBundleFinalizationStage,
  type TerminalBundleFinalizationStatusLoad,
  type TerminalBundleResolution,
  type TerminalBundleSignaturePurpose,
  type TerminalBundleTransport,
  type TerminalBundleTransportIdentity,
  type TerminalBundleVerification,
  type VerifyFinalizedTerminalBundleInput,
  isCanonicalSettlementIdentity,
  isCanonicalSolanaSignature,
  resolveSettlementEventIdentity,
  type AuthenticatedSettlementLedgerEvent,
  type VerifiedX402ReceiptBinding,
  type SettlementEventIdentityContext,
  type SettlementEventIdentityDecision,
  type SettlementEventIdentityDeps,
  type SettlementEventIdentityResolution,
  verifyFinalizedSessionSettlement,
  type SessionSettlementDisposition,
  type SessionSettlementIdentityBinding,
  type SessionSettlementNativeSessionBinding,
  type SessionSettlementNativeObservation,
  type SessionSettlementRevalidation,
  type SessionSettlementFinalityPolicy,
  type SessionSettlementRailPin,
  type SessionSettlementContext,
  type SessionSettlementNativeProofRef,
  type FinalizedSessionSettlement,
  type SessionSettlementNativeProofLookup,
  type SessionSettlementVerificationProvider,
  type AuthenticatedSessionSettlementObservation,
  type VerifiedSessionSettlement,
  type SessionSettlementVerification,
  createCompletedBuyerBundleCounterSignature,
  finalizeCompletedBuyerBundleCore,
  type AnchoredBuyerBundle,
  type BuyerBundleLookup,
  type BuyerBundleFinalizationProvider,
  type CreateCompletedBuyerBundleCounterSignatureInput,
  type FinalizeCompletedBuyerBundleInput,
  type FinalizedBuyerBundle,
  createCompletedCounterpartyBundleCounterSignature,
  finalizeCompletedCounterpartyBundleCore,
  type AnchoredCounterpartyBundle,
  type CounterpartyBundleFinalizationProvider,
  type CounterpartyBundleLookup,
  type CounterpartyBundleRole,
  type CounterpartySigningSessionParty,
  type CreateCompletedCounterpartyBundleCounterSignatureInput,
  type FinalizeCompletedCounterpartyBundleInput,
  type FinalizedCounterpartyBundle,
  advanceCompletedBuyerBundleDurable,
  getBuyerBundleFinalizationStatus,
  buyerBundleFinalizationCheckpointKey,
  type BuyerBundleEffectFence,
  type BuyerBundleSignaturePurpose,
  type BuyerBundleFencedSigner,
  type DurableBuyerBundleFinalizationInput,
  type DurableBuyerBundleFinalizationProvider,
  type AuthenticatedBundleRolePublication,
  type DurableFinalizedBuyerBundle,
  type BuyerBundleTransportIdentity,
  type BuyerBundleTransportResolution,
  type BuyerCounterSignaturePublication,
  type BuyerBundleTransport,
  type BuyerBundleSignatureReconciliation,
  type BuyerCounterSignaturePublicationReconciliation,
  type BuyerBundleAnchorReconciliation,
  type BuyerBundleBindingPublicationReconciliation,
  type BuyerBundleFinalizationDurability,
  type BuyerBundleFinalizationStage,
  type DurableBuyerBundleFinalizationProgress,
  type BuyerBundleCheckpointState,
  type BuyerBundleFinalizationStatusLoad,
  buildSignedArtifact,
  verifySignedArtifact,
  type SignedArtifact,
  type Signer,
  type Verifier,
  runFulfilmentCore,
  sellerFulfilmentId,
  type SellerAttestationRef,
  type SellerBundleContribution,
  type SellerDeliveredAccess,
  type SellerDeliveredArtifact,
  type SellerResolvedDelivery,
  type SellerResolvedPayloadAttestation,
  type SellerPreparedDelivery,
  type SellerDeliveryPreparation,
  type SellerDeliverableSpec,
  type SellerDeliveryAttempt,
  type SellerDeliverySubmission,
  type SellerDeliveryReconciliation,
  type SellerDeliveryPhase,
  type SellerEvidenceAnchorResult,
  type SellerFulfilmentAgreement,
  type SellerFulfilmentAuditSourceResolver,
  type SellerFulfilmentDeps,
  type SellerFulfilmentListing,
  type SellerFulfilmentRequest,
  type SellerFulfilmentResolution,
  type SellerFulfilmentResult,
  type SellerPayloadAttestationRecord,
  type SellerPayloadAttestationResolution,
  type SellerPayloadVerificationCapabilityDecision,
  type SellerPayloadVerificationCapabilityInput,
  type SellerVerificationResult,
  type SellerSessionPhaseHandlerResult,
  type SellerSessionPhaseEntry,
  type SellerFulfilmentSessionRecord,
  type SellerDeliverySuccessEvidence,
  type SellerDeliveryFailureEvidence,
  type SignedSellerDeliveryEvidence,
  runDurableFulfilmentCore,
  runDurableFulfilmentToDeliveryReady,
  advanceDeliveryFinalisation,
  resumeDeliveryFinalisation,
  verifyDurableSellerTerminalResult,
  projectDurableSellerAuditPending,
  getSellerFulfilmentStatus,
  getDeliveryFinalisationStatus,
  sellerFulfilmentCheckpointKey,
  type DurableSellerFulfilmentDeps,
  type VerifiedDurableDeliverable,
  type DeliveryFinalisationHandle,
  type DeliveryReadyResult,
  type DurableDeliveryReadyRunResult,
  type DeliveryFinalisationMilestone,
  type DeliveryFinalisationStatusLoad,
  type DurableSellerTerminalVerification,
  type ProjectDurableSellerAuditPendingInput,
  type VerifiedDurableSellerAuditPendingProjection,
  type SellerEffectAuthoritativeAbsence,
  type SellerEffectFence,
  type SellerFinalSessionReceiptInput,
  type SellerFinalSessionReceiptResult,
  type SellerFulfilmentDurability,
  type SellerFulfilmentCheckpointState,
  type SellerFulfilmentStatusLoad,
  type VerifyDurableSellerTerminalResultInput,
  type VerifiedDurableSellerTerminalResult,
  publishListingCore,
  type PublishListingDeps,
  type PublishListingResult,
} from "./agent/index.js";

// Settlement rails (SR-4): x402 reference rail + the runSession `settle` bridge.
export {
  PRIOR_PAYMENT_DISPOSITION_SEPARATOR,
  CONCRETE_PAYMENT_PHASES,
  validateAlternativePaymentListing,
  projectAlternativePaymentPipeline,
  deriveAlternativeFixedPriceAgreement,
  buildPriorPaymentDisposition,
  priorPaymentDispositionHash,
  priorPaymentDispositionAddress,
  priorPaymentDispositionReference,
  priorPaymentDispositionSignedBytes,
  verifyPriorPaymentReplacement,
  validateAlternativePaymentRetry,
  verifyAlternativePaymentAudit,
  authorizeAlternativePayment,
  type AlternativePaymentVerdict,
  type AlternativePaymentDecision,
  type AlternativePaymentListingLike,
  type AlternativeRailDefinition,
  type AlternativeArtifactAuthentication,
  type AlternativeDefinitionResolution,
  type AlternativeRegistrySnapshot,
  type AlternativePaymentListingDeps,
  type ResolvedAlternativeRail,
  type AlternativePaymentListingAdmission,
  type AlternativePaymentListingResult,
  type AlternativePaymentAgreementLike,
  type AlternativePaymentProjectionDeps,
  type AlternativeSessionDefinitionPin,
  type AlternativePaymentProjection,
  type AlternativePaymentProjectionResult,
  type AlternativeFixedPriceAgreementInput,
  type AlternativeFixedPriceAgreementDeps,
  type AlternativeFixedPriceAgreementSuccess,
  type AlternativeFixedPriceAgreementResult,
  type UnsignedPriorPaymentDisposition,
  type PriorPaymentDispositionSigner,
  type PriorPaymentAuthorizationClosure,
  type PriorPaymentDispositionIssuanceDeps,
  type PriorPaymentDispositionReceipt,
  type PriorPaymentDispositionResolution,
  type PriorAgreementResolution,
  type PriorPaymentExecutionAuthority,
  type PriorPaymentReplacementDeps,
  type PriorPaymentReplacementAdmission,
  type PriorPaymentReplacementResult,
  type AlternativePaymentRetryInput,
  type AlternativePaymentAuditBundleLike,
  type AlternativePaymentAuditDeps,
  type AlternativePaymentAuthorizationInput,
  createX402Rail,
  x402Settle,
  x402SettleCore,
  termsMatch,
  type X402Rail,
  type X402RailConfig,
  type X402SettleParams,
  type X402SettleCoreDeps,
  type X402PaidEffectFence,
  type X402ClientLike,
  type X402PaymentRequired,
  type X402PaymentRequirement,
  type X402SettlementResponse,
  assertDacsPublicHttpsUrlV1,
  createDacsPublicHttpsFetchV1,
  requestX402OutboundV1,
  resolveDacsPublicHostV1,
  X402OutboundTransportError,
  type DacsPublicHttpsDependenciesV1,
  type DacsPublicHttpsFetchOptionsV1,
  type DacsPublicHttpsGetInitV1,
  type DacsPublicHttpsGetV1,
  type DacsPublicHttpsRequestV1,
  type X402OutboundRequestInput,
  type X402OutboundResponse,
  type X402OutboundHeaderInit,
  type X402PaymentHeaderMode,
  type X402OutboundTransportMode,
  type X402OutboundTransportPolicy,
  createX402Paywall,
  x402PaywallCore,
  x402PaywallFulfilmentKey,
  x402PaywallSettlementKey,
  type X402Paywall,
  type X402PaywallConfig,
  type X402PaywallCoreDeps,
  type X402PaywallExpectedTerms,
  type X402PaywallFacilitatorLike,
  type X402PaywallFulfilment,
  type X402PaywallFulfilmentContext,
  type X402PaywallHandleInput,
  type X402PaywallHandlers,
  type X402PaywallHttpAdapter,
  type X402PaywallHttpContext,
  type X402PaywallPaymentPayload,
  type X402PaywallPaymentRequirements,
  type X402PaywallProcessResult,
  type X402PaywallResponse,
  type X402PaywallResult,
  type X402PaywallAuthorizationContext,
  type X402PaywallPaymentAuthorization,
  type X402PaywallPreSettlementAuthorization,
  type X402PaywallPreSettlementContext,
  type X402PaywallServerLike,
  type X402PaywallSettlementClaim,
  type X402PaywallSettlementIntent,
  type X402PaywallSettlementLoad,
  type X402PaywallSettlementOutcome,
  type X402PaywallSettlementReconciliation,
  type X402PaywallSettlementResult,
  type X402PaywallSettlementStore,
  X402_PAYWALL_SETTLEMENT_STORE_VERSION,
  createFsX402PaywallSettlementStore,
  type FsX402PaywallSettlementStoreOptions,
  createEvmErc20Rail,
  evmErc20Settle,
  evmErc20SettleCore,
  createIdempotencyStore,
  createInMemorySettlementLog,
  settlementBindingHash,
  settlementKey,
  type SettlementBinding,
  type SettlementEffectFence,
  type SettlementIdempotencyStore,
  type SettlementIdempotencyStoreOptions,
  type SettlementIntentClaim,
  type SettlementIntentLease,
  type SettlementLeaseToken,
  type SettlementLog,
  type SettlementNotInvokedResult,
  type SettlementOutcomeRecord,
  type SettlementOutcomeWrite,
  type SettlementReconcile,
  type SettlementReplayAuthorization,
  type SettlementRecoveryGrant,
  type EvmErc20Rail,
  type EvmErc20RailConfig,
  type EvmErc20SettleParams,
  type EvmTransferClient,
  deriveAp2IdempotencyKey,
  deriveAp2TransactionId,
  ap2CheckoutSignaturePolicy,
  ap2RegistrationEligibility,
  admitAp2MandateChain,
  evaluateAp2TransactionBinding,
  advanceAp2Settlement,
  createInMemoryAp2BindingStore,
  type Ap2CheckoutSignatureGeneration,
  type Ap2CheckoutSignaturePolicyInput,
  type Ap2RegistrationCapabilities,
  type Ap2MandateAdmissionInput,
  type Ap2MandateAdmission,
  type Ap2BindingState,
  type Ap2TransactionBinding,
  type Ap2TransactionBindingDecision,
  type Ap2VerifiedCheckoutMandate,
  type Ap2VerifiedPaymentMandate,
  type Ap2MandateVerification,
  type Ap2MandateVerifier,
  type Ap2SettlementIntent,
  type Ap2ReceiptAttestation,
  type Ap2CapturedSettlement,
  type Ap2BindingLease,
  type Ap2BindingClaim,
  type Ap2BindingWrite,
  type Ap2BindingStore,
  type Ap2EffectFence,
  type Ap2ProviderSubmission,
  type Ap2AttestedProviderStatus,
  type Ap2ProviderAdapter,
  type AdvanceAp2SettlementInput,
  type Ap2SettlementProgress,
  ERC20_TRANSFER_EVENT_TOPIC,
  verifyEvmTransferFinality,
  type EvmCanonicalBlock,
  type EvmTransferFinalityClient,
  type EvmTransferFinalityObservation,
  type EvmTransferFinalityRequest,
  type EvmTransferLog,
  type EvmTransferReceipt,
  X402_BUYER_SETTLEMENT_STORE_VERSION,
  x402BuyerSettlementKey,
  createX402BuyerSettlementIntent,
  assertX402BuyerSettlementIntent,
  x402BuyerSettlementAuthenticationHash,
  createInMemoryX402BuyerSettlementStore,
  createFsX402BuyerSettlementStore,
  prepareX402BuyerSettlement,
  createX402BuyerPaidRequestTransport,
  createDacsX402BuyerEvmChallengeClient,
  advanceX402BuyerSettlement,
  type X402BuyerJson,
  type X402BuyerPaymentRequirements,
  type X402BuyerSettlementIntent,
  type X402BuyerSettlementIntentDraft,
  type X402BuyerSignedEventReference,
  type X402BuyerCapturedSettlement,
  type X402BuyerTerminalFailureKind,
  type X402BuyerSettlementOutcome,
  type X402BuyerLeaseToken,
  type X402BuyerSettlementLease,
  type X402BuyerSettlementLoad,
  type X402BuyerSettlementClaim,
  type X402BuyerRecoveryGrant,
  type X402BuyerDisclosureWrite,
  type X402BuyerOutcomeWrite,
  type X402BuyerSettlementStore,
  type X402BuyerEffectFence,
  type X402BuyerAuthorizationLookup,
  type X402BuyerAuthorizationReconciliation,
  type X402BuyerIntentAuthorization,
  type X402BuyerAuthorizationProvider,
  type X402BuyerSettlementDisclosure,
  type X402BuyerPaidRequestResult,
  type X402BuyerPaidRequestTransport,
  type X402BuyerSettlementProgress,
  type AdvanceX402BuyerSettlementInput,
  type FsX402BuyerSettlementStoreOptions,
  type X402BuyerChallengeClient,
  type X402BuyerPreparationAuthority,
  type DacsX402BuyerEvmChallengeClient,
  type DacsX402BuyerEvmChallengeClientConfig,
  type PrepareX402BuyerSettlementInput,
  type PrepareX402BuyerSettlementDeps,
  type X402BuyerSettlementPreparation,
  type X402BuyerPaidRequestTransportOptions,
  type X402BuyerHeaderInit,
  EIP3009_AUTHORIZATION_USED_TOPIC,
  EIP3009_AUTHORIZATION_CANCELED_TOPIC,
  ERC20_TRANSFER_TOPIC,
  createX402BuyerEvmAuthorizationProvider,
  type X402BuyerEip3009Authorization,
  type X402BuyerEvmFinalityHead,
  type X402BuyerEvmLog,
  type X402BuyerEvmTransactionReceipt,
  type X402BuyerEvmAuthorizationState,
  type X402BuyerEvmBlockAncestry,
  type X402BuyerEvmReadClient,
  type X402BuyerEvmIntentAuthority,
  type X402BuyerEvmSignatureVerifier,
  type X402BuyerEvmUnusedConfirmer,
  type X402BuyerEvmDisclosureRecovery,
  type X402BuyerEvmAuthorizationProviderOptions,
  type X402BuyerEvmAuthorizationObservation,
  createViemX402BuyerEvmReadClient,
  type ViemX402BuyerEvmReadClientOptions,
  createPayD402Rail,
  payD402Settle,
  payD402SettleCore,
  termsMatchD402,
  PAY_D402_AVAILABILITY,
  type PayD402Rail,
  type PayD402RailConfig,
  type PayD402SettleParams,
  type PayD402SettleCoreDeps,
  type D402ClientLike,
  type D402PaymentRequirement,
  type D402SettlementResult,
  createPayDemRail,
  PayDemIncludedNonceVisibilityError,
  payDemSettle,
  payDemSettleCore,
  type PayDemRail,
  type PayDemRailConfig,
  type PayDemPreparedTransfer,
  type PayDemSettlementRecoveryContext,
  type PayDemReconciledSettlement,
  type PayDemSettlementReconcile,
  type PayDemSettleParams,
  type DemosNativeClient,
  type DemosTransferResult,
} from "./rails/index.js";

// Transport-independent seller intake (DACS-3 §8.5/§8.6; DACS-4
// §9.5.1/§9.5.7..§9.5.9). Pure verification only: no server, transport,
// payment submission, or application callback is coupled to this surface.
export {
  respondToFixedPriceAgreementProposalDurable,
  durableSellerFixedPriceAgreementCheckpointKey,
  type SellerFixedPriceAgreementEffectFence,
  type DurableSellerFixedPriceAgreementSigner,
  type DurableSellerFixedPriceAgreementInput,
  type SellerFixedPriceAgreementContextQuery,
  type SellerFixedPriceAgreementContextResolution,
  type SellerFixedPriceAgreementSignatureReconciliationInput,
  type SellerFixedPriceAgreementContributionTransport,
  type DurableSellerFixedPriceAgreementDurability,
  type DurableSellerFixedPriceAgreementResponse,
  type DurableSellerFixedPriceAgreementStage,
  type DurableSellerFixedPriceAgreementProgress,
  deriveX402ReceiptCommitment,
  verifyX402ReceiptClaim,
  X402_V1_CHAIN_IDS,
  createPayDemSellerObserver,
  observePayDemTransferCore,
  verifySellerPaymentIntake,
  canonicalSellerSettlementId,
  createInMemorySellerReceiptStore,
  SELLER_RECEIPT_STORE_VERSION,
  createFsSellerReceiptStore,
  isSellerFulfilmentHandoff,
  sellerFulfilmentCandidateHash,
  SELLER_FULFILMENT_AUDIT_SOURCE_COMMITMENT_SEPARATOR,
  isSellerFulfilmentAuditSource,
  isSellerFulfilmentSessionRecord,
  isValidSellerReceiptClaim,
  sellerFulfilmentAuditSourceHash,
  x402Eip3009Nonce,
  createX402SellerSpine,
  type X402ReceiptCommitment,
  type X402ReceiptDisposition,
  type X402ResponseHeader,
  type X402ReceiptEvidence,
  type X402ReceiptVerification,
  type PayDemObservationClient,
  type PayDemSellerObserver,
  type PayDemSellerObserverConfig,
  type SellerPaymentIntakeDisposition,
  type SellerFulfilmentPermit,
  type SellerSessionBindingGuarantee,
  type SellerDemosTxRef,
  type SellerLegacyX402TxRef,
  type SellerX402EventTxRef,
  type SellerX402TxRef,
  type SellerPaymentTxRef,
  type SellerPaymentFinality,
  type SellerPaymentEvidenceInput,
  type SellerPaymentClaim,
  type SellerPaymentIntakeInput,
  type CommittedAgreementResolution,
  type SellerPayloadVerificationProducerAdmission,
  type SellerListingAtCommitResolution,
  type IdentityBundleResolution,
  type SellerDemosRailDefinition,
  type SellerX402RailDefinition,
  type SellerSupportedRailDefinition,
  type SellerRailResolution,
  type AddressResolution,
  type DestinationBindingResolution,
  type DemosTransferObservation,
  type X402SessionBinding,
  type X402TransferObservation,
  type SellerReceiptClaim,
  type SellerFulfilmentHandoff,
  type SellerFulfilmentHandoffEnvelope,
  type SellerFulfilmentHandoffV2,
  type SellerFulfilmentAuditSourceCommitmentV1,
  type SellerFulfilmentAuditArtifactsV1,
  type SellerFulfilmentAuditSourceV1,
  type SellerFulfilmentExpectedVerifyResult,
  type SellerFulfilmentVetRequirementInvocation,
  type SellerReceiptClaimResult,
  type SellerReceiptPermitResult,
  type SellerReceiptInspectionResult,
  type SellerReceiptStore,
  type SellerFulfilmentReceiptStore,
  type FsSellerReceiptStoreOptions,
  type SellerPaymentAuthorization,
  type SellerPaymentCommitmentBinding,
  type SellerSettlementIdentity,
  type X402ReceiptExtensionVerification,
  type X402SettlementChainClassification,
  type SellerPaymentIntakeDeps,
  type SellerPaymentIntakeResult,
  publishSellerSessionSettlement,
  type SellerSessionSettlementPublicationRequest,
  type SellerSessionSettlementNativeProofBinding,
  type SellerSessionSettlementAuthenticatedNativeProof,
  type SellerSessionSettlementNativeProofAuthentication,
  type SellerSessionSettlementSignedEvidenceResolution,
  type SellerSessionSettlementAnchorResult,
  type SellerSessionSettlementEvidenceResolution,
  type SellerSessionSettlementEvidenceSigner,
  type SellerSessionSettlementAnchorWriter,
  type SellerSessionSettlementPublicationDeps,
  type SellerSessionSettlementPublicationResult,
  type X402SellerCommittedSessionResolution,
  type X402SellerCommittedSessionScope,
  type X402SellerPaymentPermitAuthorization,
  type X402SellerRenderedResponse,
  type X402SellerDeliveryReadyResponseContext,
  type X402SellerResponseContext,
  type X402SellerSpine,
  type X402SellerSpineOptions,
  finalizeCompletedSellerBundleCore,
  prepareCompletedSellerBundleCounterSignatureRequest,
  verifyCompletedSellerBundleCounterSignatureRequest,
  verifyFinalizedSellerBundleReadOnly,
  type SellerBundleVerificationDisposition,
  type SellerBundleDependencyKind,
  type CompletedSellerPhaseHandlerResult,
  type CompletedSellerPhaseEntry,
  type CompletedSellerSessionParty,
  type AuditPendingSellerSessionRecord,
  type CompletedSellerSessionArtifacts,
  type CompletedSellerVetRequirementInvocation,
  type SellerBundleDependencySource,
  type FinalizedSellerBundleDependency,
  type SellerBundleDependencyRequirement,
  type SellerBundleDependencyLookup,
  type AnchoredSellerBundle,
  type SellerBundleLookup,
  type SellerBundleBindingLookup,
  type SellerBundleBindingPublication,
  type SellerPaymentPhaseIndexResolution,
  type SellerCompositeVerificationDeps,
  type SellerBundleFinalizationProvider,
  type SellerBundleFinalizationReadProvider,
  type FinalizeCompletedSellerBundleInput,
  type VerifyCompletedSellerBundleCounterSignatureRequestInput,
  type VerifyFinalizedSellerBundleInput,
  type CompletedSellerBundleCounterSignatureRequest,
  type FinalizedSellerBundle,
  finalizeCompletedSellerBundleDurable,
  getSellerBundleFinalizationStatus,
  sellerBundleFinalizationCheckpointKey,
  type SellerBundleEffectFence,
  type SellerBundleFencedSigner,
  type SellerBundleDurableSigner,
  type SellerBundleFencedComponentSigner,
  type FinalizeCompletedSellerBundleDurableInput,
  type DurableSellerBundleFinalizationProvider,
  type SellerBundleFinalizationRole,
  type SellerBundleSignaturePurpose,
  type SellerBundleSignatureReconciliation,
  type SellerBundleAnchorReconciliation,
  type SellerBundleBindingPublicationReconciliation,
  type SellerBundleFinalizationDurability,
  type SellerBundleCheckpointState,
  type SellerBundlePublicationCheckpointState,
  type SellerBundleFinalizationStatusLoad,
} from "./seller/index.js";

// Steward registries (T12/T13): resolve + pin steward-signed rails/recipes,
// dispatch the money path by rail kind.
export {
  RAIL_REGISTRY_INDEX_ADDRESS,
  getAuthenticatedRailProvenance,
  isAuthenticatedRailDefinition,
  resolveRail,
  resolveRecipe,
  RECIPE_REGISTRY_INDEX_ADDRESS,
  authenticateRecipeRegistrySnapshot,
  selectLatestRecipeAtSessionStart,
  resolveHistoricalRecipeFromSnapshot,
  isAuthenticatedRecipeRegistrySnapshot,
  isLatestRecipeSelection,
  isHistoricalRecipeResolution,
  type AuthenticatedRecipeDescriptor,
  type AuthenticatedRailDefinition,
  type CurrentRailRegistryIndex,
  type RailRegistryAuthorityInput,
  type RailRegistryDefinitionAuthorityInput,
  type RailRegistryAuthorityVerification,
  type RailRegistryDefinitionRef,
  type RailRegistryIndexDocument,
  type RailRegistryProvenance,
  type RailRegistrySelectionProvider,
  type RegistryResolveDeps,
  type RecipeRegistryRecipeRef,
  type RecipeRegistryIndexDocument,
  type CurrentRecipeRegistryIndex,
  type RecipeRegistryAuthorityVerification,
  type RecipeRegistryAuthorityInput,
  type RecipeRegistrySelectionProvider,
  type AuthenticatedRecipeRegistryEntry,
  type RecipeFamilyIdentity,
  type RecipeRegistryProvenance,
  type AuthenticatedRecipeRegistrySnapshot,
  type LatestRecipeSelector,
  type LatestRecipeSelection,
  type HistoricalRecipeResolution,
  RECIPE_ANCHORING_PHASES,
  classifyRecipeAnchoringPhase,
  assessRegistryGovernanceDisclosure,
  evaluatePinnedRecipeGovernance,
  type RecipeAnchoringPhase,
  type RecipeAnchoringPhaseClassification,
  type RegistryGovernanceRepresentation,
  type RegistryGovernanceDisclosureInput,
  type RegistryGovernanceDisclosureDecision,
  type PinnedRecipeGovernanceInput,
  type PinnedRecipeGovernanceDecision,
  settleFromRail,
  type RailDispatchOptions,
  type AssetSpec,
  type Availability,
  type CrossChainRoute,
  type NetworkSpec,
  type RailDefinition,
  type RailDescriptor,
  type RailGovernance,
  type RailSelector,
  type RailType,
  type RecipeDescriptor,
  type RecipeGovernance,
  type RecipeSelector,
  type Registry,
} from "./registry/index.js";

// Artifact model (T3): spine artifact types, kind→separator registry, validators.
export {
  type ArtifactKind,
  type ClaimRef,
  type ClaimRequirement,
  type VerifyResultRef,
  type BundleClaim,
  type PresentationSignature,
  type IdentityBundle,
  type BundleRequirement,
  type Price,
  type Delivery,
  type Listing,
  type ListingEnvelope,
  type ListingSignature,
  type RevocationMarker,
  type RevocationBinding,
  type ListingDraft,
  type LegacyMvpListing,
  type ReadableListing,
  type ListingPin,
  type ListingTerms,
  type SubstrateRequirement,
  type PhaseType,
  type PhaseStep,
  type VerificationMethod,
  type DeliverableSpec,
  type DeliverableRef,
  type PaymentRailRef,
  type AlternativePaymentPhase,
  type PriceTerm,
  type PricingSpec,
  type VerificationDecision,
  type VerificationMethodKind,
  type VerifyResultSignature,
  type VerifyResult,
  type SupplementarySignal,
  type VerificationWarningCode,
  type VerificationWarning,
  type CompositeVerificationRecord,
  type LegacyVerifyResultEntry,
  type LegacyCompositeVerificationRecord,
  type ReadableCompositeVerificationRecord,
  type AgreementDocument,
  type AgreementParty,
  type AgreementSignature,
  type AgreementTerms,
  type PayoutBinding,
  type PriceAnchor,
  type FeeRecurrencePeriod,
  type FeeItem,
  type FeeSchedule,
  type PayeeBoundAgreementTerms,
  type PayeeBoundAgreementDocument,
  type AgreementArtifact,
  type AttestationAnchorKind,
  type AttestationAnchor,
  type AttestationRef,
  type ListingRef,
  type ChainTxRef,
  type TxRef,
  type PaymentAmount,
  type SettlementFinalityModel,
  type SettlementCommitmentLevel,
  type SettlementFinalityParameters,
  type SettlementFinality,
  type ComponentSignatureAlgorithm,
  type ComponentSignature,
  type PriorPaymentDisposition,
  type CommitmentRecord,
  type FinalityCommitmentRecord,
  type AgreementCommitmentRecord,
  type AnchorTransactionRef,
  type AnchorReceiptEvidence,
  type AnchorLifecycleState,
  // The top-level `AnchorReceipt` name is the long-standing substrate write
  // receipt. Keep that API stable and expose CORE §5.1's portable receipt under
  // an unambiguous alias; the artifacts subpath retains its normative name.
  type AnchorReceipt as ProtocolAnchorReceipt,
  type ArtifactSignature,
  type PaymentPhaseType,
  type DeliveryPhaseType,
  type SettlementEvidence,
  type Rating,
  type BundleParty,
  type PhaseSummaryEntry,
  type LegacyBundlePhaseEntry,
  type BundlePhaseOutcome,
  type BundlePhaseErrorClass,
  type BundleSignature,
  type AttestationBundle,
  type FaultAttestationBundle,
  type AnyAttestationBundle,
  type BundleBinding,
  type BundlePartyRole,
  type FaultedParty,
  type LegacyMvpAttestationRef,
  type LegacyMvpAgreementDocument,
  type LegacyMvpTxRef,
  type LegacyMvpSettlementEvidence,
  type LegacyMvpPhaseSummaryEntry,
  type LegacyMvpAttestationBundle,
  type LegacyMvpFaultAttestationBundle,
  type LegacyMvpAnyAttestationBundle,
  ARTIFACT_SEPARATORS,
  BUNDLE_BINDING_SEPARATOR,
  RATING_SEPARATOR,
  separatorFor,
  isListing,
  isListingEnvelope,
  isListingPipelineValid,
  isPaymentRailRef,
  isRevocationMarker,
  isRevocationBinding,
  isListingDraft,
  isLegacyMvpListing,
  readListingArtifact,
  isListingPublicEndpoint,
  isIdentityBundle,
  isBundleRequirement,
  isVerificationMethod,
  isDeliverableSpec,
  isPhaseStep,
  isListingTerms,
  isPricingSpec,
  isVerifyResult,
  isVerifyResultRef,
  isSupplementarySignal,
  isVerificationWarning,
  isCompositeVerificationRecord,
  isLegacyCompositeVerificationRecord,
  readCompositeVerificationRecord,
  isAgreementDocument,
  isPayeeBoundAgreementDocument,
  isAgreementArtifact,
  isCommitmentRecord,
  isFinalityCommitmentRecord,
  isReadableFinalityCommitmentRecord,
  isAgreementCommitmentRecord,
  isAnchorReceipt,
  isReadableAnchorReceipt,
  isAttestationRef,
  isChainTxRef,
  isSettlementEvidence,
  isAttestationBundle,
  isFaultAttestationBundle,
  isBundleBinding,
  isAnyAttestationBundle,
  isLegacyMvpAttestationRef,
  isLegacyMvpAgreementDocument,
  isLegacyMvpTxRef,
  isLegacyMvpSettlementEvidence,
  isLegacyMvpAttestationBundle,
  isLegacyMvpFaultAttestationBundle,
  isLegacyMvpAnyAttestationBundle,
  COMPONENT_SIGNATURE_ALGORITHMS,
  isCanonicalBase64Url,
  isComponentSignature,
  buildComponentSignature,
  signComponentArtifact,
  verifyComponentSignature,
  type ComponentSignedArtifact,
  type ComponentSigner,
  type BuildComponentSignatureOptions,
  type ComponentSignatureStatus,
  type ComponentSignatureMalformedReason,
  type ComponentSignatureUnresolvedReason,
  type ComponentSignatureInvalidReason,
  type ComponentSignatureVerification,
  type VerifyComponentSignatureInput,
  type VerifyComponentSignatureDeps,
} from "./artifacts/index.js";
